CREATE TABLE IF NOT EXISTS users
(
    id CHARACTER VARYING(100) NOT NULL UNIQUE,
    status CHARACTER VARYING(100) NOT NULL,
    first_name CHARACTER VARYING(100) NOT NULL,
    username CHARACTER VARYING(100) NULL
)